name: Docker Latest

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    tags-ignore:
      - "*"
    branches-ignore:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 14-alpine
          - 16-alpine

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    name: Test & Tag Latest (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build test image
        id: docker_test
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: localhost:5000/renokico/clusteer:latest-${{ matrix.node }}
          build-args: |
            VERSION=${{ matrix.node }}

      - name: Test
        run: |
          docker run -d -p 8080:8080 localhost:5000/renokico/clusteer:${{ github.sha }}-${{ matrix.node }}
          sleep 5
          curl --silent -XGET --fail http://127.0.0.1:8080?url=https://example.com&actions=[]&html=1
          curl --silent -XGET --fail http://127.0.0.1:8080/usage

      - name: Build final image
        id: docker_final
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: quay.io/renokico/clusteer:latest-${{ matrix.node }}
          build-args: |
            VERSION=${{ matrix.node }}
