name: Docker Release

on:
  push:
    tags:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 14-alpine
          - 16-alpine

    name: Tag Release (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/renokico/clusteer
          tags: |
            type=semver,pattern={{version}}-${{ matrix.node }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.node }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Compute GitHub tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push (node:${{ matrix.node }})
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ matrix.node }}
